[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"
baseURL = "https://mynamissapbas.github.io/"
languageCode = "th-th"
title = "YourName Portfolio"


[params]
    mainSections = ["post"]
    
    [params.sidebar]
        emoji = "ðŸš€"
        subtitle = "Computer Science Student"
        [params.sidebar.avatar]
            enabled = true
            local = true
            src = "img/avatar.jpg"

    [params.appearance]
        defaultTheme = "dark"

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
